version: '3'
services:
    logstash:
        container_name: logstash
        image: logstash:5.6.9-mod
        restart: always
        volumes:
            - ./etc/logstash/conf.d:/etc/logstash/conf.d
        command: -f /etc/logstash/conf.d -r
        network_mode: host
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "10"
