version: '3'

services:
    openldap:
        container_name: openldap
        image: osixia/openldap
        restart: always
        # network_mode: host
        ports: 
            - "8389:389"
        environment:
            LDAP_ORGANISATION: "Long Tom" 
            LDAP_DOMAIN: "longtom.com"
            LDAP_ADMIN_PASSWORD: "admin" 
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "10"

    phpldapadmin:
        container_name: phpldapadmin
        image: osixia/phpldapadmin
        restart: always
        # network_mode: host
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: openldap
        links:
            - openldap
        ports: 
            - "8443:443"
            - "8080:80"
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "10"
    
