version: '3'

services:
    influxdb:
        container_name: influxdb
        image: influxdb:1.5.2
        restart: always
        environment:
            - INFLUXDB_DB="logstash"
            - INFLUXDB_ADMIN_USER="root"
            - INFLUXDB_ADMIN_PASSWORD="root"
            - INFLUXDB_USER="admin"
            - INFLUXDB_USER_PASSWORD="admin"
            - INFLUXDB_HTTP_WRITE_TRACING="true"
        network_mode: host
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "10"
    
    statsd:
        container_name: statsd
        image: shakr/statsd-influxdb
        restart: always
        network_mode: host
        environment:
            - INFLUXDB_USERNAME="root"
            - INFLUXDB_PASSWORD="root"
            - INFLUXDB_DATABASE="logstash"
            - INFLUXDB_HOST="127.0.0.1"
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "10"

    grafana:
        container_name: grafana
        image: grafana/grafana
        restart: always
        network_mode: host
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "10"
